version: '3.7'
services:
  jupyter:
    container_name: glue_jupyter
    command: /home/glue_user/jupyter/jupyter_start.sh
    environment:
      - DISABLE_SSL=true
    image: amazon/aws-glue-libs:glue_libs_3.0.0_image_01
    ports:
      - '8080:8080'
    restart: always
    volumes:
      - ${AWS_PROFILE_FOLDER}:/home/glue_user/.aws
      - ./src/aws_glue/:/home/glue_user/workspace/jupyter_workspace/