CREATE DATABASE TCS;

USE TCS;

-- TCS.dbo.CEP definition

-- Drop table

-- DROP TABLE TCS.dbo.CEP;

CREATE TABLE TCS.dbo.CEP (
	CEP int NOT NULL,
	UF nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CIDADE nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BAIRRO nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LOGRADOURO nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT CEP_PK PRIMARY KEY (CEP)
);


-- TCS.dbo.CONDICAO_PAGAMENTO definition

-- Drop table

-- DROP TABLE TCS.dbo.CONDICAO_PAGAMENTO;

CREATE TABLE TCS.dbo.CONDICAO_PAGAMENTO (
	ID_CONDICAO int NOT NULL,
	DESCRICAO nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	QTD_PARCELAS int NULL,
	CONSTRAINT PK__CONDICAO__5F755ED9D0D721F0 PRIMARY KEY (ID_CONDICAO)
);


-- TCS.dbo.ENDERECOS_FORNECEDORES definition

-- Drop table

-- DROP TABLE TCS.dbo.ENDERECOS_FORNECEDORES;

CREATE TABLE TCS.dbo.ENDERECOS_FORNECEDORES (
	ID_ENDERECO_FORNECEDOR int IDENTITY(1,1) NOT NULL,
	CEP nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ID_FORNECEDOR int NULL,
	ID_TIPO_ENDERECO int NULL,
	NUM_ENDERECO nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COMPLEMENTO nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__ENDERECO__0FD927202F5570DB PRIMARY KEY (ID_ENDERECO_FORNECEDOR)
);


-- TCS.dbo.FORNECEDORES definition

-- Drop table

-- DROP TABLE TCS.dbo.FORNECEDORES;

CREATE TABLE TCS.dbo.FORNECEDORES (
	ID_FORNECEDOR int IDENTITY(1,1) NOT NULL,
	NOME nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CNPJ nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EMAIL nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TELEFONE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__FORNECED__0AE4966DA5C3CD98 PRIMARY KEY (ID_FORNECEDOR)
);


-- TCS.dbo.NOTAS_FISCAIS_ENTRADA definition

-- Drop table

-- DROP TABLE TCS.dbo.NOTAS_FISCAIS_ENTRADA;

CREATE TABLE TCS.dbo.NOTAS_FISCAIS_ENTRADA (
	ID_NF_ENTRADA int IDENTITY(1,1) NOT NULL,
	NUMERO_NF varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ID_FORNECEDOR int NULL,
	ID_CONDICAO int NULL,
	DATA_EMISSAO date NULL,
	VALOR_NET decimal(10,2) NULL,
	VALOR_TRIBUTO decimal(10,2) NULL,
	VALOR_TOTAL decimal(10,2) NULL,
	NOME_ITEM varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	QTD_ITEM int NULL,
	CONSTRAINT PK__NOTAS_FI__765187A037F1AE1B PRIMARY KEY (ID_NF_ENTRADA)
);


-- TCS.dbo.PROGRAMACAO_PAGAMENTO definition

-- Drop table

-- DROP TABLE TCS.dbo.PROGRAMACAO_PAGAMENTO;

CREATE TABLE TCS.dbo.PROGRAMACAO_PAGAMENTO (
	ID_PROG_PAGAMENTO int IDENTITY(1,1) NOT NULL,
	ID_NF_ENTRADA int NULL,
	DATA_VENCIMENTO date NULL,
	NUM_PARCELA int NOT NULL,
	VALOR_PARCELA decimal(21,13) NULL,
	STATUS_PAGAMENTO varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK__PROGRAMA__DF2B84A5D953EC6B PRIMARY KEY (ID_PROG_PAGAMENTO)
);


-- TCS.dbo.TIPO_ENDERECO definition

-- Drop table

-- DROP TABLE TCS.dbo.TIPO_ENDERECO;

CREATE TABLE TCS.dbo.TIPO_ENDERECO (
	ID_TIPO_ENDERECO int NOT NULL,
	DESCRICAO nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SIGLA nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__TIPO_END__52D259A52CB400B7 PRIMARY KEY (ID_TIPO_ENDERECO)
);


-- TCS.dbo.dbo##CEP definition

-- Drop table

-- DROP TABLE TCS.dbo.dbo##CEP;

CREATE TABLE TCS.dbo.dbo##CEP (
	CEP int NULL,
	UF nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CIDADE nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BAIRRO nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LOGRADOURO nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);