CREATE DATABASE TCS;

USE TCS;

-- TCS.dbo.CEP definition
CREATE TABLE TCS.dbo.CEP (
    CEP int NOT NULL, -- Modificado para int
    UF nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CIDADE nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    BAIRRO nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    LOGRADOURO nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT CEP_PK PRIMARY KEY (CEP)
);

-- TCS.dbo.CONDICAO_PAGAMENTO definition
CREATE TABLE TCS.dbo.CONDICAO_PAGAMENTO (
    ID_CONDICAO int NOT NULL,
    DESCRICAO nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    QTD_PARCELAS int NULL,
    CONSTRAINT PK__CONDICAO__5F755ED9D0D721F0 PRIMARY KEY (ID_CONDICAO)
);

-- TCS.dbo.ENDERECOS_FORNECEDORES definition ajustada para usar CEP como INT
CREATE TABLE TCS.dbo.ENDERECOS_FORNECEDORES (
    ID_ENDERECO_FORNECEDOR int IDENTITY(1,1) NOT NULL,
    CEP int NULL, -- Ajustado para int para corresponder à tabela CEP
    ID_FORNECEDOR int NULL,
    ID_TIPO_ENDERECO int NULL,
    NUM_ENDERECO nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    COMPLEMENTO nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT PK__ENDERECO__0FD927202F5570DB PRIMARY KEY (ID_ENDERECO_FORNECEDOR)
);

-- TCS.dbo.FORNECEDORES definition
CREATE TABLE TCS.dbo.FORNECEDORES (
    ID_FORNECEDOR int IDENTITY(1,1) NOT NULL,
    NOME nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CNPJ nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, -- Confirmado como nvarchar(20)
    EMAIL nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TELEFONE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT PK__FORNECED__0AE4966DA5C3CD98 PRIMARY KEY (ID_FORNECEDOR)
);

-- TCS.dbo.NOTAS_FISCAIS_ENTRADA definition
CREATE TABLE TCS.dbo.NOTAS_FISCAIS_ENTRADA (
    ID_NF_ENTRADA int IDENTITY(1,1) NOT NULL,
    NUMERO_NF varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    ID_FORNECEDOR int NULL, -- Tipo compatível com FORNECEDORES.ID_FORNECEDOR
    ID_CONDICAO int NULL, -- Tipo compatível com CONDICAO_PAGAMENTO.ID_CONDICAO
    DATA_EMISSAO date NULL,
    VALOR_NET decimal(10,2) NULL,
    VALOR_TRIBUTO decimal(10,2) NULL,
    VALOR_TOTAL decimal(10,2) NULL,
    NOME_ITEM varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    QTD_ITEM int NULL,
    CONSTRAINT PK__NOTAS_FI__765187A037F1AE1B PRIMARY KEY (ID_NF_ENTRADA)
);

-- TCS.dbo.PROGRAMACAO_PAGAMENTO definition
CREATE TABLE TCS.dbo.PROGRAMACAO_PAGAMENTO (
    ID_PROG_PAGAMENTO int IDENTITY(1,1) NOT NULL,
    ID_NF_ENTRADA int NULL, -- Tipo compatível com NOTAS_FISCAIS_ENTRADA.ID_NF_ENTRADA
    DATA_VENCIMENTO date NULL,
    NUM_PARCELA int NOT NULL,
    VALOR_PARCELA decimal(21,13) NULL,
    STATUS_PAGAMENTO varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    CONSTRAINT PK__PROGRAMA__DF2B84A5D953EC6B PRIMARY KEY (ID_PROG_PAGAMENTO)
);

-- TCS.dbo.TIPO_ENDERECO definition
CREATE TABLE TCS.dbo.TIPO_ENDERECO (
    ID_TIPO_ENDERECO int NOT NULL,
    DESCRICAO nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    SIGLA nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT PK__TIPO_END__52D259A52CB400B7 PRIMARY KEY (ID_TIPO_ENDERECO)
);


-- Adicionando chaves estrangeiras

-- CEP -> ENDERECOS_FORNECEDORES
ALTER TABLE TCS.dbo.ENDERECOS_FORNECEDORES
ADD CONSTRAINT FK_ENDERECOS_FORNECEDORES_CEP
FOREIGN KEY (CEP) REFERENCES TCS.dbo.CEP(CEP);

-- FORNECEDORES -> ENDERECOS_FORNECEDORES
ALTER TABLE TCS.dbo.ENDERECOS_FORNECEDORES
ADD CONSTRAINT FK_ENDERECOS_FORNECEDORES_FORNECEDORES
FOREIGN KEY (ID_FORNECEDOR) REFERENCES TCS.dbo.FORNECEDORES(ID_FORNECEDOR);

-- TIPO_ENDERECO -> ENDERECOS_FORNECEDORES
ALTER TABLE TCS.dbo.ENDERECOS_FORNECEDORES
ADD CONSTRAINT FK_ENDERECOS_FORNECEDORES_TIPO_ENDERECO
FOREIGN KEY (ID_TIPO_ENDERECO) REFERENCES TCS.dbo.TIPO_ENDERECO(ID_TIPO_ENDERECO);

-- CONDICAO_PAGAMENTO -> NOTAS_FISCAIS_ENTRADA
ALTER TABLE TCS.dbo.NOTAS_FISCAIS_ENTRADA
ADD CONSTRAINT FK_NOTAS_FISCAIS_ENTRADA_CONDICAO_PAGAMENTO
FOREIGN KEY (ID_CONDICAO) REFERENCES TCS.dbo.CONDICAO_PAGAMENTO(ID_CONDICAO);

-- FORNECEDORES -> NOTAS_FISCAIS_ENTRADA
ALTER TABLE TCS.dbo.NOTAS_FISCAIS_ENTRADA
ADD CONSTRAINT FK_NOTAS_FISCAIS_ENTRADA_FORNECEDORES
FOREIGN KEY (ID_FORNECEDOR) REFERENCES TCS.dbo.FORNECEDORES(ID_FORNECEDOR);

-- NOTAS_FISCAIS_ENTRADA -> PROGRAMACAO_PAGAMENTO
ALTER TABLE TCS.dbo.PROGRAMACAO_PAGAMENTO
ADD CONSTRAINT FK_PROGRAMACAO_PAGAMENTO_NOTAS_FISCAIS_ENTRADA
FOREIGN KEY (ID_NF_ENTRADA) REFERENCES TCS.dbo.NOTAS_FISCAIS_ENTRADA(ID_NF_ENTRADA);